name: CMake Build
run-name: Build Sandman

on: 
   push:
      paths: ['sandman/**']
   pull_request:
   workflow_dispatch:

jobs:
  build_Sandman_executable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NCurses
        run: sudo apt-get install --yes libncurses-dev

      - name: Install Mosquitto MQTT Broker
        run: sudo apt-get install --yes libmosquitto-dev

      - name: Install CMake
        run: sudo apt-get install --yes cmake

      - name: Generate CMake Build Files
        run: cmake -S sandman -B sandman/build -DENABLE_GPIO=OFF

      - name: Build Sandman with CMake
        run: cmake --build sandman/build
